/*
 * MTIMER0_config.h
 *
 * NTI GRADUATION PROJECT "SMART HOME SYSTEM "
 *
 *  	 Authors: 1- Hassan Abdelazim Abdelsalam
 *	    	 	  2- Abdelrahman Dardeer
 *
 */

#ifndef MTIMER0_MTIMER0_CONFIG_H_
#define MTIMER0_MTIMER0_CONFIG_H_

#define FCPU 16UL
/*
 * 	Please Configure Timer clk :
 *
  	MTIMER0_NO_CLK 0
	MTIMER0_PRESCALER_1
	MTIMER0_PRESCALER_8
	MTIMER0_PRESCALER_64
	MTIMER0_PRESCALER_256
	MTIMER0_PRESCALER_1024
	MTIMER0_EXTCLK_FALL_EDEG
	MTIMER0_EXTCLK_RISE_EDEG
*/
#define MTIMER0_CLK	 	MTIMER0_PRESCALER_1024

/*
 * 	Please Configure TIMER0 MODE:
 *
 	 MTIMER0_NORMAL_MODE
 	 MTIMER0_CTC_MODE
 	 MTIMER0_FAST_PWM_MODE
 	 MTIMER0_PHASE_CORRECT_MODE
 */

#define MTIMER0_MODE	MTIMER0_FAST_PWM_MODE

/*
 * Please Configure TIMER0 WAVEFORM:
 *
 *	 MTIMER0_OC0_DISCONNECTED
 *	 MTIMER_OC0_TOGGLE
 *	 MTIMER0_OC0_CLEAR
 *	 MTIMER0_OCO_SET
 *
 *	 Configure PWD mode:
 *
 *   MTIMER_OCO_NONINVERTING
 * 	 MTIMER_OCO_INVERTING
 */

#define MTIMER0_OC0_MODE	MTIMER_OCO_INVERTING


#endif /* MTIMER0_MTIMER0_CONFIG_H_ */
